# Generated by Django 3.1.1 on 2020-09-11 04:23

from django.db import migrations, models
import first.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('math', models.IntegerField()),
                ('english', models.IntegerField()),
                ('science', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, validators=[first.models.min_length_3])),
                ('address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
